### ISSUE TITLE
support for additional_info in track_metadata

### ISSUE THREAD

**Issue by jpathy** [ocharles/listenbrainz-client#1]
https://listenbrainz.readthedocs.io/en/production/dev/json.html#payload-json-details

**Comment by ocharles** [comment]
Thanks, I never got round to doing this bit. Do you need this functionality, or is it a nice-to-have?

**Comment by jpathy** [comment]
I guess, it's nice to have for now.

**Comment by ocharles** [comment]
Released as 1.1.0.
